server:
  port: 0
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application_instance_id:${random.value}}
    leaseRenewalIntervalInSeconds: 10
    preferIpAddress: true

spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411
  datasource:
    

logging:
  level:
    root: ERROR
    org.springframework.web: INFO
    com.sun.mail.smtp: ERROR
  file: /var/logs/api-communications.log

mail:
  from: noreply@inatlas.com
    password: aragon224
  support:
    einforma: jordi.medina@inatlas.com
    production: jordi.medina@inatlas.com
  team:
    leader: roberto.zazo@inatlas.com
  test:
    leader: mauri.arevalo@inatlas.com
  developers:
    default: jordi.medina@inatlas.com
  inatlas:
    informa:
      test: jordi.medina@inatlas.com
  newcredits:
    confirmation:
      informa:
        spain: jordi.medina@inatlas.com
          cc: jordi.medina@inatlas.com
        portugal: jordi.medina@inatlas.com
          cc: jordi.medina@inatlas.com
  credit:
    requested:
      informa:
        spain: jordi.medina@inatlas.com
          cc: jordi.medina@inatlas.com
        portugal: jordi.medina@inatlas.com
          cc: jordi.medina@inatlas.com

---

spring:
  profiles: local

---

spring:
  profiles: docker
  zipkin:
    base-url: http://zipkin-server:9411
  rabbitmq:
    host: rabbitmq38

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka


