server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application_instance_id:${random.value}}

zuul:
  routes:
    productos:
      service-id: servicio-productos
      path: /api/productos/**
    items:
      service-id: servicio-items
      path: /api/items/**
    usuarios:
      service-id: servicio-usuarios
      path: /api/usuarios/**
    oauth:
      service-id: servicio-oauth-server
      path: /api/security/**
      sensitive-headers: Cookie,Set-Cookie

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 70000
      
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000

config:
  security:
    oauth:
      jwt:
        key: algun_codigo_super_secreto_como_12345

spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    #base-url: http://localhost:9411/
    sender:
      type: rabbit
