server:
  port: 0
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application_instance_id:${random.value}}
    leaseRenewalIntervalInSeconds: 10
    preferIpAddress: true

spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    sender:
      type: rabbit

---

spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://mysql8:3306/productos?serverTimezone=Europe/Madrid&allowPublicKeyRetrieval=true
    username: root
    password: sasa
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
            
logging.level.org.hibernate.SQL: debug
