server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application_instance_id:${random.value}}
    leaseRenewalIntervalInSeconds: 10
    preferIpAddress: true

config:
  security:
    oauth:
      client:
        id: frontendapp
        secret: 12345
      jwt:
        key: algun_codigo_super_secreto_como_12345

spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411

---

spring:
  profiles: docker
  zipkin:
    base-url: http://zipkin-server:9411
  rabbitmq:
    host: rabbitmq38

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
